### ISSUE TITLE
can't host game

### ISSUE THREAD

**Issue by coder0107git** [bahaaEldeen1999/uno-multiplayer#4]
I was trying to host a game on the website and it said 
"[here is your game id make sure to send it to your friends so they can join you
creating the game....](https://user-images.githubusercontent.com/76132013/103383576-75716f80-4ab0-11eb-9925-949618d220bd.png)" with no game code and when I clicked the okay button and on the next screen in the bottom right corner it said game id, and when I clicked on it, it said "[your game id is : undefined](https://user-images.githubusercontent.com/76132013/103383569-6db1cb00-4ab0-11eb-89c1-e8b224db2be1.png)". If you can can fix it it would be appreciated. Thanks!
![Screenshot 2020-12-30 at 3 03 25 PM](https://user-images.githubusercontent.com/76132013/103383576-75716f80-4ab0-11eb-9925-949618d220bd.png)
![Screenshot 2020-12-30 at 3 03 33 PM](https://user-images.githubusercontent.com/76132013/103383569-6db1cb00-4ab0-11eb-89c1-e8b224db2be1.png)

**Comment by bahaaEldeen1999** [comment]
thanks for reporting the issue i will check to see if the database still running or not and i will let you know

**Comment by bahaaEldeen1999** [comment]
Ok i migrated the database from deactivated matlab account to new monogDB Atlas account and it should be all working now

**Comment by liadev213** [comment]
Currently, I get the same error.
Could you fix it?
Thanks!

**Comment by bahaaEldeen1999** [comment]
I took the server down last month as i needed the resources in some other project, but i started it now and the game is back online

**Comment by liadev213** [comment]
Thank you!
Still, I have an error when starting the app:
`/home/node/uno-multiplayer/node_modules/mongoose/lib/connection.js:582
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
    ^

MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
`

**Comment by bahaaEldeen1999** [comment]
are you trying to run it locally ? as i just checked the web app and it seems to be working fine

**Comment by liadev213** [comment]
I tried it inside a ubuntu Docker container. Other node applications works fine there.

**Comment by bahaaEldeen1999** [comment]
You need to set the needed environment variables
